# Generated by Django 5.0.2 on 2024-02-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0002_remove_airport_code_remove_airport_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_datetime',
            new_name='date',
        ),
    ]
